name: phonetic_translator
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (Required)
  firebase_core: ^3.8.0

  # Cloud Firestore (Database)
  cloud_firestore: ^5.5.0

  # Firebase Authentication
  firebase_auth: ^5.3.3

  # Other useful packages
  provider: ^6.1.1  # For state management

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true